### ISSUE TITLE
async test description

### ISSUE THREAD

**Issue by julia-bougaev** [rmurphey/js-assessment#134]
In the description of the second test for async behavior it's not mentioned  that a structure of the response is response.people (not response.guys or whatever).

**Comment by ashleygwilliams** [comment]
thanks for filing this issue! we definitely have a bit of an issue with the descriptions of tests. do you have a suggestion on what we should write? (if you're interested, i'd be happy to walk you through writing a PR)

**Comment by jacalata** [comment]
I think there are two good options here, first you could just add a hint on viewing the object like
// to see what the response looks like, log it to the console
or you could be more specific like 
  		// this url returns an object like this
  		//  { people: [ { name } ] }

**Comment by tonesfrommars** [comment]
I just got this test to pass and I'm a relative beginner to js.
The cool thing about the slightly cryptic descriptions is it has compelled me to read the tests themselves in order to grok the expected outcomes. I'd say the hint about logging to console is more than enough in this case. Too much guidance takes away the "real world" flavor of the experience.

**Comment by rmurphey** [comment]
I'm going to close this in agreement with @tonesfrommars -- part of the goal here is to get people to read the tests.
