### ISSUE TITLE
Additional tests for numbers-related skills

### ISSUE THREAD

**Issue by rmurphey** [rmurphey/js-assessment#52]
- dealing with inaccuracies re decimals
- binary operations
- "random" number between two numbers

**Comment by jacobroufa** [comment]
@rmurphey is this still a valid issue? I see that there are number tests that deal both with decimal accuracy and binary operations. What more had you envisioned when writing this issue?

**Comment by notno** [comment]
I. L nun e.g. B
/
M.p.h. E e. /-. ,--m

On Sat, May 9, 2015 at 8:11 AM, Jake Roufa <notifications@github.com> wrote:
@rmurphey [https://github.com/rmurphey] is this still a valid issue? I see that there are number tests that deal both
with decimal accuracy and binary operations. What more had you envisioned when
writing this issue?

—
Reply to this email directly or view it on GitHub
[https://github.com/rmurphey/js-assessment/issues/52#issuecomment-100503744] .[https://github.com/notifications/beacon/ADANgGoqBjxtLXzpoAu72iVKTHvMoYRVks5oHhslgaJpZM4AJ6ml.gif]

**Comment by ashleygwilliams** [comment]
hey @notno! could you... clarify? (trying to discern if this is spam, but your profile looks legit so maybe this is a butt-comment or an encoding issue?)

**Comment by rmurphey** [comment]
@jacobroufa I'm not sure what I meant by this 2.5 years ago :) If it seems resolved, it's probably resolved.

**Comment by ashleygwilliams** [comment]
:+1: closing per @rmurphey's comment

**Comment by jmeas** [comment]
I understood @rmurphey 's comment to be an 'if we feel this is done, then it is done,' rather than an 'okay this is done.' 

Although we might not know the specifics of the original intention of the post, the post does list three specific types of skills to test:

1. bitwise operators
2. floating point arithmetic
3. pseudo-randomness

looking at the answers, we test for one [here](https://github.com/rmurphey/js-assessment-answers/blob/master/app/numbers.js#L6) and [here](https://github.com/rmurphey/js-assessment-answers/blob/master/app/numbers.js#L16-L18), and two [here](https://github.com/rmurphey/js-assessment-answers/blob/master/app/numbers.js#L23-L43). What's absent is the third thing on the list, so  if we think that it's important to test that, then we might want to reopen this.

tho' to be honest I can't think of a solid way to test a random number generator :P

**Comment by ashleygwilliams** [comment]
word @jmeas, i'm gonna keep this closed and open a new issue just for the randomness. it's hard to test random number generation, but not impossible? i figure we can have that a convo in another thread
